export function b64Encode(s:string){return btoa(Array.from(new TextEncoder().encode(s),b=>String.fromCharCode(b)).join(''));}
export function b64Decode(s:string){const raw=atob(s.trim());return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(raw,c=>c.charCodeAt(0)));}
export function ipv4(cidr:string){const m=cidr.trim().match(/^(\d{1,3}(?:\.\d{1,3}){3})\/(\d{1,2})$/);if(!m)throw Error('Saisis une adresse IPv4 au format adresse/préfixe.');const oct=m[1].split('.').map(Number),p=Number(m[2]);if(oct.some(n=>n>255)||p>32)throw Error('Adresse IPv4 ou préfixe invalide.');const ip=oct.reduce((a,n)=>a*256+n,0),mask=p===0?0:(0xffffffff<<(32-p))>>>0,net=(ip&mask)>>>0,broad=(net|(~mask>>>0))>>>0,fmt=(n:number)=>[24,16,8,0].map(s=>(n>>>s)&255).join('.'),count=2**(32-p);return {mask:fmt(mask),network:fmt(net),broadcast:fmt(broad),first:p>=31?fmt(net):fmt(net+1),last:p>=31?fmt(broad):fmt(broad-1),count};}
export function unixDate(value:string,unit:'s'|'ms'){const n=Number(value);if(!Number.isFinite(n))throw Error('Horodatage invalide.');const d=new Date(unit==='s'?n*1000:n);if(Number.isNaN(d.getTime()))throw Error('Date hors limites.');return {utc:d.toISOString(),local:d.toLocaleString()};}
const ambiguity=/[O0Il1]/g;
function secureIndex(max:number){const range=0x1_0000_0000,limit=range-range%max;const b=new Uint32Array(1);do{crypto.getRandomValues(b);}while(b[0]>=limit);return b[0]%max;}
export function password(length:number,sets:string[],exclude:boolean){if(!Number.isInteger(length)||length<8||length>128)throw Error('La longueur doit être comprise entre 8 et 128.');if(!sets.length)throw Error('Choisis au moins une catégorie.');const chars=sets.map(x=>exclude?x.replace(ambiguity,''):x);if(chars.some(x=>!x))throw Error('Une catégorie ne contient plus de caractères après exclusion.');if(length<chars.length)throw Error('La longueur est trop courte pour garantir chaque catégorie.');const pool=[...new Set(chars.join(''))],out=Array.from({length},()=>pool[secureIndex(pool.length)]);for(let i=0;i<chars.length;i++)out[i]=chars[i][secureIndex(chars[i].length)];for(let i=out.length-1;i>0;i--){const j=secureIndex(i+1);[out[i],out[j]]=[out[j],out[i]];}return out.join('');}
export function contrast(a:string,b:string){const l=(x:string)=>{const n=parseInt(x.slice(1),16),v=[n>>16,(n>>8)&255,n&255].map(c=>c/255).map(c=>c<=.04045?c/12.92:((c+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2];};const [x,y]=[l(a),l(b)].sort((p,q)=>q-p);return (x+.05)/(y+.05);}
export function readStore<T>(key:string,fallback:T):T{try{const v=localStorage.getItem(key);if(!v)return fallback;const parsed=JSON.parse(v);return parsed?.version===1?parsed.data:fallback;}catch{return fallback;}}
export function writeStore(key:string,data:unknown){try{localStorage.setItem(key,JSON.stringify({version:1,data}));return true;}catch{return false;}}
