import {useState} from 'react';
import {contrast,readStore,writeStore} from '../lib/core';
const rand=()=>Math.floor(Math.random()*256).toString(16).padStart(2,'0').toUpperCase();
const color=()=>`#${rand()}${rand()}${rand()}`;
const excuses=['Ça fonctionnait avant que je vérifie.','Le cache a pris une décision personnelle.','Le bug est timide : il disparaît en démo.','J’ai corrigé un problème adjacent par accident.','Le serveur compile ses émotions.','C’était dans la spécification. Enfin, une spécification.','Le déploiement a réveillé un ancien bug.','J’ai confondu production et préproduction. Le site aussi.','Le correctif est prêt, il attend son propre correctif.','Le câble avait une opinion différente.','La base de données a médité un peu trop longtemps.','J’ai optimisé le problème jusqu’à le rendre invisible.'];
const wordSets={Geek:['Pixel','Kernel','Byte','Syntaxe','Stack','Cache','Daemon','Bit'],Fantasy:['Dragon','Rune','Mage','Grimoire','Golem','Phénix','Elfe','Nébuleuse'],Absurde:['Loutre','Cornichon','Canard','Chaussette','Turbine','Baguette','Poulpe','Fromage']};
export default function Generators({type}:{type:string}){
 const [colors,C]=useState(Array.from({length:5},color)),[locks,K]=useState([false,false,false,false,false]),[angle,A]=useState(135),[gradientCount,GC]=useState(3),[quote,Q]=useState('Les idées aussi ont besoin d’un environnement de test.'),[author,U]=useState('Sofiane Dehimi'),[style,T]=useState(0),[result,R]=useState(''),[pseudoStyle,PS]=useState<keyof typeof wordSets>('Geek'),[pseudos,PN]=useState<string[]>([]),[favs,V]=useState<string[]>(readStore('sf.excuse-favorites',[])),[currentExcuse,CE]=useState(excuses[0]);
 const copy=async(t:string)=>{try{await navigator.clipboard.writeText(t);R('Copié dans le presse-papiers.');}catch{R('Copie indisponible. Sélectionne le texte manuellement.');}};
 if(type==='palette')return <section className="tool-panel"><div className="eyebrow">GÉNÉRATEUR</div><h2>Palettes de couleurs</h2><div className="swatches">{colors.map((c,i)=><div key={i} className="swatch" style={{background:c}}><span>{c}</span><button onClick={()=>K(locks.map((x,j)=>j===i?!x:x))} aria-label={`${locks[i]?'Déverrouiller':'Verrouiller'} ${c}`}>{locks[i]?'Déverrouillée':'Verrouiller'}</button><button onClick={()=>copy(c)}>Copier HEX</button></div>)}</div><button onClick={()=>C(colors.map((c,i)=>locks[i]?c:color()))}>Générer la palette</button><button className="secondary" onClick={()=>copy(`:root {\n${colors.map((c,i)=>`  --couleur-${i+1}: ${c};`).join('\n')}\n}`)}>Copier variables CSS</button><h3>Contraste WCAG</h3><div className="row"><label>Texte<select id="fg">{colors.map(c=><option key={c}>{c}</option>)}</select></label><label>Fond<select id="bg">{colors.map(c=><option key={c}>{c}</option>)}</select></label><button className="secondary" onClick={()=>{const ratio=contrast((document.querySelector('#fg') as HTMLSelectElement).value,(document.querySelector('#bg') as HTMLSelectElement).value);R(`${ratio.toFixed(2)}:1 · ${ratio>=7?'AAA (texte normal)':ratio>=4.5?'AA (texte normal)':ratio>=3?'AA (grand texte uniquement)':'Ne satisfait pas AA pour le texte courant'}`)}}>Calculer</button></div><p role="status">{result}</p></section>;
 if(type==='gradient')return <section className="tool-panel"><div className="eyebrow">GÉNÉRATEUR</div><h2>Dégradés CSS</h2><div className="swatches"><label>Nombre de couleurs<select value={gradientCount} onChange={e=>GC(+e.target.value)}>{[2,3,4].map(n=><option key={n} value={n}>{n} couleurs</option>)}</select></label>{colors.slice(0,gradientCount).map((c,i)=><label key={i}>Couleur {i+1}<input type="color" value={c} onChange={e=>C(colors.map((v,j)=>i===j?e.target.value:v))}/></label>)}</div><label>Angle <input type="range" min="0" max="360" value={angle} onChange={e=>A(+e.target.value)}/> {angle}°</label><div className="gradient-preview" style={{background:`linear-gradient(${angle}deg,${colors.slice(0,gradientCount).join(',')})`}}/><button onClick={()=>copy(`background: linear-gradient(${angle}deg, ${colors.slice(0,gradientCount).join(', ')});`)}>Copier le CSS</button><p role="status">{result}</p></section>;
 if(type==='quote')return <section className="tool-panel"><h2>Cartes de citations</h2><label>Texte<textarea value={quote} onChange={e=>Q(e.target.value)}/></label><label>Auteur<input value={author} onChange={e=>U(e.target.value)}/></label><label>Style<select value={style} onChange={e=>T(+e.target.value)}><option value="0">Nuit cyan</option><option value="1">Violet laboratoire</option><option value="2">Papier clair</option></select></label><div className={`quote-card quote-${style}`}><span>SONFIRE / LAB</span><blockquote>{quote}</blockquote><b>{author}</b></div><button onClick={()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=630;const ctx=canvas.getContext('2d');if(!ctx){R('Canvas indisponible.');return;}ctx.fillStyle=style===2?'#f5f2eb':style===1?'#211b38':'#10131c';ctx.fillRect(0,0,1200,630);ctx.fillStyle=style===2?'#087f91':'#67e8f9';ctx.font='24px monospace';ctx.fillText('SONFIRE / LAB',80,85);const font=quote.length>300?27:quote.length>140?35:48;ctx.font=`bold ${font}px sans-serif`;ctx.fillStyle=style===2?'#171923':'#f4f6fc';const words=quote.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>1040&&line){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);const lineHeight=font*1.28,start=250-(Math.min(lines.length,12)*lineHeight)/2;lines.slice(0,12).forEach((text,i)=>ctx.fillText(text,80,start+i*lineHeight));if(lines.length>12){ctx.font='21px sans-serif';ctx.fillText('… le texte continue dans l’aperçu',80,570);}ctx.font='24px sans-serif';ctx.fillStyle=style===2?'#586274':'#aab2c4';ctx.fillText(author.slice(0,70),80,590);canvas.toBlob(blob=>{if(!blob){R('Export PNG impossible.');return;}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='carte-sonfire.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);R('Carte PNG téléchargée.');},'image/png');}}>Exporter PNG</button><p role="status">{result}</p></section>;
 if(type==='nickname')return <section className="tool-panel"><h2>Générateur de pseudos</h2><label>Style<select value={pseudoStyle} onChange={e=>PS(e.target.value as keyof typeof wordSets)}>{Object.keys(wordSets).map(x=><option key={x}>{x}</option>)}</select></label><button onClick={()=>PN(Array.from({length:5},()=>`${wordSets[pseudoStyle][Math.floor(Math.random()*wordSets[pseudoStyle].length)]}${wordSets[pseudoStyle][Math.floor(Math.random()*wordSets[pseudoStyle].length)]}${Math.floor(Math.random()*99)}`))}>Générer 5 pseudos</button>{pseudos.map(name=><div className="result-row" key={name}><span>{name}</span><button className="secondary" onClick={()=>copy(name)}>Copier</button></div>)}<small>Suggestions locales, disponibilité non vérifiée.</small><p role="status">{result}</p></section>;
 const favorite=(s:string)=>{const next=favs.includes(s)?favs.filter(x=>x!==s):[...favs,s];V(next);writeStore('sf.excuse-favorites',next);R(next.includes(s)?'Excuse ajoutée aux favoris.':'Excuse retirée des favoris.');};return <section className="tool-panel"><h2>Excuses de développeur</h2><div className="result-box">{currentExcuse}</div><div className="row"><button onClick={()=>{CE(excuses[Math.floor(Math.random()*excuses.length)]);R('');}}>Générer</button><button className="secondary" onClick={()=>copy(currentExcuse)}>Copier</button><button className="secondary" onClick={()=>favorite(currentExcuse)}>{favs.includes(currentExcuse)?'★ Retirer le favori':'☆ Ajouter aux favoris'}</button></div>{favs.length>0&&<div><h3>Favoris · {favs.length}</h3>{favs.map(f=><div className="result-row" key={f}><span>{f}</span><button className="secondary" onClick={()=>favorite(f)}>Retirer</button></div>)}</div>}<p role="status">{result}</p></section>;
}
