import {useMemo,useState} from 'react';
import {BookOpen,Copy,Heart,Play,Search,ShieldAlert,Star} from 'lucide-react';
import {linuxCards,categories} from '../data/linux';
import {readStore,writeStore} from '../lib/core';

const normalize=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

export default function Library(){
 const [q,Q]=useState(''),[cat,C]=useState('Toutes'),[selected,S]=useState(''),[favs,F]=useState<string[]>(readStore('sf.favorites',[])),[demo,D]=useState(''),[onlyFavorites,OF]=useState(false),[status,ST]=useState('');
 const list=useMemo(()=>linuxCards.filter(x=>(cat==='Toutes'||x.category===cat)&&(!onlyFavorites||favs.includes(x.id))&&(q===''||normalize(`${x.command} ${x.description} ${x.tags.join(' ')}`).includes(normalize(q)))),[q,cat,onlyFavorites,favs]);
 const item=linuxCards.find(x=>x.id===selected);
 const toggle=(id:string)=>{const next=favs.includes(id)?favs.filter(x=>x!==id):[...favs,id];F(next);writeStore('sf.favorites',next);};
 const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);ST('Commande copiée. Vérifie les placeholders, droits et chemins avant usage.');}catch{ST('Presse-papiers indisponible : sélectionne la commande dans la fiche pour la copier manuellement.');}};
 return <div className="library-page">
  <header className="library-heading"><div className="eyebrow"><BookOpen size={15}/> RÉFÉRENCE INTERACTIVE · {linuxCards.length} FICHES</div><h1>Mémo Linux</h1><p>Des commandes concrètes, avec leur contexte et leurs précautions. Tous les exemples sont simulés : rien n’est exécuté sur ton appareil.</p></header>
  <div className="library-layout">
   <section className="tool-panel library-catalog" aria-label="Catalogue des commandes">
    <div className="library-panel-heading"><div><div className="eyebrow">CATALOGUE LOCAL</div><h2>Trouver une commande</h2></div><span className="count-badge">{list.length} résultat{list.length===1?'':'s'}</span></div>
    <label className="search-field"><span>Commande, description ou tag</span><div><Search size={16}/><input value={q} onChange={e=>Q(e.target.value)} placeholder="Ex. DNS, gros fichiers, journal…"/></div></label>
    <div className="library-filter-row"><label>Catégorie<select value={cat} onChange={e=>C(e.target.value)}><option>Toutes</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" className={onlyFavorites?'filter-chip active':'filter-chip'} aria-pressed={onlyFavorites} onClick={()=>OF(v=>!v)}><Star size={15}/> Favoris <span>{favs.length}</span></button></div>
    <div className="linux-list" aria-label="Résultats des commandes">{list.length?list.map(x=><article className={selected===x.id?'linux-row selected':'linux-row'} key={x.id}><button type="button" className="linux-select" onClick={()=>{S(x.id);D('');ST('');}} aria-current={selected===x.id?'true':undefined}><code>{x.command}</code><span>{x.description}</span></button><button type="button" className="favorite-toggle" aria-label={favs.includes(x.id)?`Retirer ${x.command} des favoris`:`Ajouter ${x.command} aux favoris`} aria-pressed={favs.includes(x.id)} onClick={()=>toggle(x.id)}>{favs.includes(x.id)?<Heart size={17} fill="currentColor"/>:<Heart size={17}/>}</button></article>):<div className="empty-state"><Search size={20}/><b>Aucune commande trouvée</b><span>Essaie un autre terme ou retire le filtre Favoris.</span></div>}</div>
    <p className="privacy-note">Favoris enregistrés uniquement dans ce navigateur.</p>
   </section>
   <aside className="tool-panel detail-panel linux-detail" aria-label="Fiche de commande">
    {item?<><div className="detail-topline"><span className="category-pill">{item.category}</span>{item.sensitive&&<span className="warning-pill"><ShieldAlert size={13}/> À vérifier</span>}</div><h2>{item.command}</h2><p className="detail-description">{item.description}</p><h3>Syntaxe</h3><pre className="command-block"><code>{item.syntax}</code></pre><div className="detail-example-title"><h3>Exemple</h3><span>Chemin de démonstration</span></div><pre className="command-block example-block"><code>{item.example}</code></pre><div className="detail-info"><b>Options et comportement</b><p>{item.options}</p><b>Prérequis</b><p>{item.prereq}</p></div><div className={item.sensitive?'safety-callout warning':'safety-callout'}><ShieldAlert size={17}/><p>{item.sensitive?'Cette commande ou une variante peut modifier des données ou l’état du système. Contrôle la cible et relis les options avant validation.':'Cette fiche est explicative. L’exemple affiché ci-dessous est une simulation, pas une exécution réelle.'}</p></div><p className="placeholder-help">Les mots génériques comme <code>fichier</code>, <code>chemin</code>, <code>PID</code> ou <code>/dev/DEVICE</code> sont des placeholders : remplace-les par une valeur connue et vérifiée.</p><div className="row linux-actions"><button type="button" onClick={()=>copy(item.example)}><Copy size={15}/> Copier l’exemple</button><button type="button" className="secondary" onClick={()=>{D(item.output);ST('Sortie de démonstration affichée. Aucune commande n’a été lancée.');}}><Play size={15}/> Voir la sortie simulée</button></div>{demo&&<div className="simulation-panel"><div className="eyebrow">SIMULATION · AUCUNE EXÉCUTION</div><pre className="demo"><code>{demo}</code></pre></div>}<p className="status-message" role="status">{status}</p></>:<div className="detail-empty"><span className="detail-icon"><BookOpen size={22}/></span><div className="eyebrow">FICHE COMMANDE</div><h2>Le contexte avant la commande.</h2><p>Sélectionne une commande pour consulter sa syntaxe, un exemple, les options importantes et les précautions liées.</p><div className="detail-stats"><span><b>{linuxCards.length}</b> fiches vérifiées</span><span><b>{favs.length}</b> favoris locaux</span></div></div>}
   </aside>
  </div>
 </div>;
}
